---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  tags: 
    - install

- name: Install nginx
  apt:
    name: nginx
    state: present
  tags:
    - install